# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://jonaspm.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "HackCUU | 19/21 Mayo 2017"
  description: "This is a sample hackathon website that you can use by following instructions on GitHub."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Example Hacks"
  description: "This is a sample hackathon website that you can use by following instructions on GitHub."
  date:        "5 & 6 August 2017"
  location:    "Chihuahua, Chihuahua, México"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Regístrate"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Patrocina"
        href: "mailto:jonaspm_99@outlook.com"

  about:
    description: >
      HackCUU es un hackathon para estudiantes con sede en la Universidad Autónoma de Chihuahua.
      This is your opportunity to describe your event, what to expect, where it is & anything unique to your event.
      Keep it straightforward, don't make it too long.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "APRENDE."
        description: >
          Desarrolla tus habilidades como hacker del siglo 21. Siempre hay algo que aprender de los demás.
      - image: "images/image2.png"
        title: "CONSTRUYE."
        description: >
          Convierte una idea en un producto. Convierte el producto en oportunidades. Convierte las oportunidades en éxito.
      - image: "images/image3.png"
        title: "COMPARTE."
        description: >
          Comparte tu conocimiento con otros hackers y los demás compartirán el suyo contigo.

  # Frequently asked questions.
  faq:
    - question: "¿Qué es un hackathon?"
      answer: >
        Un hackathon es un maratón para inventar. Estudiantes se reunen para desarrollar soluciones
        geniales usando software y hardware durante 24 a 48 horas. No importa si eres un hacker profesional o si apenas estás empezando [todos son bienvenidos](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "¿Cuanto cuesta?"
      answer: >
        Nada. El evento es completamente gratuito!
    - question: "¿Qué debo llevar?"
      answer: >
        Todo lo que necesites para desarrollar tu idea! Desde tu computadora y gadgets, hasta tu oso de peluche!
    - question: "¿Habrá café y galletas?"
      answer: >
        Si! Tendremos un coffe break permanente, así como comidas para todos los participantes. No dejaremos que tengas el estómago vacío!
    - question: "¿Necesito ser estudiante para asistir?"
      answer: >
        Es correcto. Sólo si eres estudiante de licenciatura o si estás en tu 5to o 6to semestre de preparatoria.
    - question: "¿Dónde es el evento?"
      answer: >
        En esta edición la sede será en Seminarios de Contaduría y Administración de la Universidad Autónoma de Chihuahua.
    - question: "¿Qué es Major League Hacking?"
      answer: >
        Major League Hacking es [la liga oficial de hackathones](https://mlh.io) en América del Norte y Europa.
        Trabajamos con larededor de 200 Eventos Miembros y empoderamos a más de 70,000 estudiantes cada año.
    - question: "¿Existe un código de conducta?"
      answer: >
        Definitivamente. Es parte fundamental del proyecto. La puedes [encontrar aqui](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      Recibirás más información cuando la fecha esté cerca. :)

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
